
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.server.SqlFlexyCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPONENT = 6;
  public static final int COMA = 13;
  public static final int MENU = 12;
  public static final int PCOMA = 14;
  public static final int TITULO = 9;
  public static final int STR = 15;
  public static final int VISITSITE = 3;
  public static final int VID = 11;
  public static final int EOF = 0;
  public static final int COLSULT = 2;
  public static final int error = 1;
  public static final int TODOS = 7;
  public static final int VISITPAGE = 4;
  public static final int POPULAR = 5;
  public static final int IMG = 10;
  public static final int PARRAFO = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COLSULT",
  "VISITSITE",
  "VISITPAGE",
  "POPULAR",
  "COMPONENT",
  "TODOS",
  "PARRAFO",
  "TITULO",
  "IMG",
  "VID",
  "MENU",
  "COMA",
  "PCOMA",
  "STR"
  };
}

